CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARACTER SET = utf8;

CREATE DATABASE IF NOT EXISTS `order` DEFAULT CHARACTER SET = utf8;

CREATE DATABASE IF NOT EXISTS `inventory` DEFAULT CHARACTER SET = utf8;

CREATE DATABASE IF NOT EXISTS `payment` DEFAULT CHARACTER SET = utf8;

CREATE DATABASE IF NOT EXISTS `tx-manager` DEFAULT CHARACTER SET = utf8;