spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration

  datasource:
    url: jdbc:mysql://${mysql.address}:3306/order?nullCatalogMeansCurrent=true
    username: ${mysql.username}
    password: ${mysql.password}

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20