version: '3'
services:
  mysql:
    image: mysql:5.7.25
    tmpfs: /var/lib/mysql:rw
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--max-connections=1000',
    ]
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly no
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.6
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongouser"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
      - "MONGO_INITDB_DATABASE=mongo_test"
      - "MONGO_DATA_DIR=/data/db"
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"

  eureka-server:
    image: aista/eureka:latest
    restart: always
    ports:
      - "9000:8761"