spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/tx-manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${mysql.username}
    password: ${mysql.password}

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20